sudo: required
services:
  - docker

before_install:
  - docker build -t medaliyou/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true medaliyou/docker-react npm run test -- --coverage

deploy:
  provider: azure_web_apps
  verbose: true
  username: "$AZURE_WA_USERNAME"
  password: 
    secret: "$AZURE_WA_PASSWORD"
  site: "may.westus.cloudapp.azure.com"
  app: "docker-ubuntu-vm"
  on:
    branch: master
  

