sudo: required
services:
  - docker

before_install:
  - docker build -t medaliyou/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true medaliyou/docker-react npm run test -- --coverage




