sudo: required
services:
  - docker

before_install:
  - docker build -t medaliyou/docker-react -f Dockerfile.dev .
script:
  - docker -e CI=true run medaliyou/docker-react npm run test -- --coverage




