sudo: required
services:
  - docker

before_install:
  - docker login "$DOCKER_AZURE_REGISTRY" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

  - docker build -t chlampa.azurecr.io/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chlampa.azurecr.io/docker-react npm run test -- --coverage
  - docker tag chlampa.azurecr.io/docker-react chlampa.azurecr.io/docker-react:latest
  - docker push chlampa.azurecr.io/docker-react
 


